// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmerrzhlvfedvywqvmvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZXJyemhsdmZlZHZ5d3F2bXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTg2MzUsImV4cCI6MjA2NjAzNDYzNX0.7M0SE-LhZ6e7NHdzTHbNf2XfaEvW4yKwo1iS4UJYMR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);